### ISSUE TITLE
TypeError: Cannot read property '_id' of undefined

### ISSUE THREAD

**Issue by Khaos66** [wreiske/Rocket.Chat.App-Math#2]
I installed the lastest Rocket.Chat (2.4.0) and the math app (Version 0.0.2) from the marketplace
When I enter a simple example I only get this error in the logs
/math 2+2
```
[
  "math's executor is being executed...",
  {
    "sender": {
      "id": "xxxxxxx",
      "username": "xxxxxxxx",
      "emails": [
        {
          "address": "xxxxxxxxx",
          "verified": false
        }
      ],
      "type": 0,
      "isEnabled": true,
      "name": "xxxxxxxxx",
      "roles": [
        "admin"
      ],
      "status": "online",
      "statusConnection": "online",
      "utcOffset": 9,
      "createdAt": "2020-01-08T05:43:30.856Z",
      "updatedAt": "2020-01-09T02:17:28.370Z",
      "lastLoginAt": "2020-01-09T02:17:28.370Z"
    },
    "room": {
      "id": "xxxxxxxxx",
      "type": "d",
      "isDefault": false,
      "isReadOnly": false,
      "displaySystemMessages": true,
      "messageCount": 16,
      "createdAt": "2020-01-08T13:30:57.556Z",
      "updatedAt": "2020-01-09T02:19:35.104Z",
      "lastModifiedAt": "2020-01-09T02:19:35.070Z"
    },
    "params": [
      "2+2"
    ]
  }
]
```
```
[
  "{\"stack\":\"TypeError: Cannot read property '_id' of undefined
    at Promise.asyncApply (app/apps/server/bridges/messages.js:22:14)
    at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\",\"message\":\"Cannot read property '_id' of undefined\"}"
]
```
```
[
  "math's executor was unsuccessful."
]
```

**Comment by wreiske** [comment]
Do you mind trying the following on the Rocket.Chat server?

```curl -v https://apps.rocketbooster.net/api/rocket/math/?q=2%2B2```

Please paste the output here. It should contain

```
"response": {
        "message": "Success",
        "status": 200
    },
```

If not, you may need to figure out why your server can't communicate with apps.rocketbooster.net

**Comment by wreiske** [comment]
This seems to be an issue with the latest version of Rocket.Chat. I have contacted their developers. I'll let you know when it's fixed.

https://github.com/RocketChat/Rocket.Chat/issues/16187

**Comment by wreiske** [comment]
Please upgrade your rocket.chat to https://github.com/RocketChat/Rocket.Chat/releases/tag/2.4.1

Let me know if you have any other issues! Thanks.

**Comment by Khaos66** [comment]
Just to confirm. After upgrading Rocket.Chat to version 2.4.1 the error is gone ;)
